# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multiparser.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(896, 737)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_5.addWidget(self.label_33)
        self.gridLayout_2.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_34 = QtWidgets.QLabel(self.groupBox_7)
        self.label_34.setObjectName("label_34")
        self.verticalLayout.addWidget(self.label_34)
        self.gridLayout_2.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_7.addWidget(self.label_36)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_9.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_9.addWidget(self.label_38)
        self.gridLayout_2.addWidget(self.groupBox_6, 3, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_11.addWidget(self.label_30)
        self.label_29 = QtWidgets.QLabel(self.groupBox_10)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_11.addWidget(self.label_29)
        self.label_28 = QtWidgets.QLabel(self.groupBox_10)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_11.addWidget(self.label_28)
        self.label_40 = QtWidgets.QLabel(self.groupBox_10)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_11.addWidget(self.label_40)
        self.gridLayout_2.addWidget(self.groupBox_10, 5, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.groupBox_9)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_35 = QtWidgets.QLabel(self.groupBox_9)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.gridLayout_2.addWidget(self.groupBox_9, 5, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_10.addWidget(self.label_25)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_10.addWidget(self.label_39)
        self.gridLayout_2.addWidget(self.groupBox_8, 4, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_4.addWidget(self.label_32)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_12.addWidget(self.label_41)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_5.setTitle(_translate("Dialog", "Поток 5"))
        self.label_8.setText(_translate("Dialog", "Состояние:"))
        self.label_10.setText(_translate("Dialog", "Страна:"))
        self.label_9.setText(_translate("Dialog", "Чемпионат:"))
        self.label_33.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox_7.setTitle(_translate("Dialog", "Поток 7"))
        self.label_11.setText(_translate("Dialog", "Состояние:"))
        self.label_12.setText(_translate("Dialog", "Страна:"))
        self.label.setText(_translate("Dialog", "Чемпионат:"))
        self.label_34.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Поток 1"))
        self.label_3.setText(_translate("Dialog", "Состояние:"))
        self.label_2.setText(_translate("Dialog", "Страна:"))
        self.label_4.setText(_translate("Dialog", "Чемпионат:"))
        self.label_31.setText(_translate("Dialog", "Количество добавленнх игр:"))
        self.groupBox_3.setTitle(_translate("Dialog", "Поток 2"))
        self.label_16.setText(_translate("Dialog", "Состояние:"))
        self.label_17.setText(_translate("Dialog", "Страна:"))
        self.label_18.setText(_translate("Dialog", "Чемпионат:"))
        self.label_36.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox_6.setTitle(_translate("Dialog", "Поток 6"))
        self.label_22.setText(_translate("Dialog", "Состояние:"))
        self.label_23.setText(_translate("Dialog", "Страна:"))
        self.label_24.setText(_translate("Dialog", "Чемпионат:"))
        self.label_38.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox_10.setTitle(_translate("Dialog", "Поток 10"))
        self.label_30.setText(_translate("Dialog", "Состояние:"))
        self.label_29.setText(_translate("Dialog", "Страна:"))
        self.label_28.setText(_translate("Dialog", "Чемпионат:"))
        self.label_40.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox_9.setTitle(_translate("Dialog", "Поток 9"))
        self.label_13.setText(_translate("Dialog", "Состояние:"))
        self.label_15.setText(_translate("Dialog", "Страна:"))
        self.label_14.setText(_translate("Dialog", "Чемпионат:"))
        self.label_35.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox_8.setTitle(_translate("Dialog", "Поток 8"))
        self.label_25.setText(_translate("Dialog", "Состояние:"))
        self.label_27.setText(_translate("Dialog", "Страна:"))
        self.label_26.setText(_translate("Dialog", "Чемпионат:"))
        self.label_39.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.groupBox.setTitle(_translate("Dialog", "Поток 3"))
        self.label_6.setText(_translate("Dialog", "Состояние:"))
        self.label_7.setText(_translate("Dialog", "Страна:"))
        self.label_5.setText(_translate("Dialog", "Чемпионат:"))
        self.label_32.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.label_41.setText(_translate("Dialog", "Количество игр в базе:"))
        self.pushButton.setText(_translate("Dialog", "Обновить"))
        self.groupBox_4.setTitle(_translate("Dialog", "Поток 4"))
        self.label_19.setText(_translate("Dialog", "Состояние:"))
        self.label_21.setText(_translate("Dialog", "Страна:"))
        self.label_20.setText(_translate("Dialog", "Чемпионат:"))
        self.label_37.setText(_translate("Dialog", "Количество добавленных игр:"))
        self.pushButton_2.setText(_translate("Dialog", "ПАРСИНГ"))
